[[redirects]]
from = "https://api.rebuff.ai/api/*"
to = "https://playground.rebuff.ai/api/:splat"
status = 200
force = true

[[redirects]]
from = "https://alpha.rebuff.ai/api/*"
to = "https://playground.rebuff.ai/api/:splat"
status = 200
force = true

[[redirects]]
from = "https://rebuff.ai/api/*"
to = "https://playground.rebuff.ai/api/:splat"
status = 200
force = true

[[redirects]]
from = "https://rebuff.ai/"
to = "https://rebuff.unicornplatform.page/"
status = 200
force = true
