version: '3'
services:
  qabot:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${CUSTOM_PORT}:7000"
    networks:
      - qabot
    # container_name: qabot-app

networks:
  qabot:
    driver: bridge
