version: "3"

services:
    pg_container:
        image: postgres:16.1
        restart: always
        environment:
            PGUSER: postgres
            POSTGRES_PASSWORD: "root"
        ports:
            - "5432:5432"
        networks:
            - eval-network
        healthcheck: # https://stackoverflow.com/questions/65115627/safe-ways-to-specify-postgres-parameters-for-healthchecks-in-docker-compose
                        # https://docs.docker.com/compose/compose-file/05-services/#depends_on
            test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
            interval: 1s
            timeout: 60s
            retries: 50
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
    llm_guard_eval:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./output:/app/output
        networks:
            - eval-network
        depends_on:
            pg_container:
                condition: service_healthy
networks:
    eval-network:
        driver: bridge
