version: '3'
services:
  prompt-db:
    image: postgres:16.1
    restart: always
    environment:
        PGUSER: postgres
        POSTGRES_PASSWORD: "root"
    ports:
        - "5432:5432"
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck: # https://stackoverflow.com/questions/65115627/safe-ways-to-specify-postgres-parameters-for-healthchecks-in-docker-compose
                 # https://docs.docker.com/compose/compose-file/05-services/#depends_on
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 1s
      timeout: 60s
      retries: 50
