version: "3"

services:
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "root"
        ports:
            - "5050:80"
        network_mode: "host"
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    pgadmin-data:
