version: "3"

services:
    pg_container:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "5432:5432"
        network_mode: "host"
